development:
  dialect: postgres
  database: timeslice_development
  user: pgapp
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://pgapp:postgres@127.0.0.1:5432/timeslice_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://pgapp:postgres@127.0.0.1:5432/timeslice_production?sslmode=disable"}}
